[package]
name = "tetanus-turn"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
tetanus-core = { path = "../core" }
tetanus-session = { path = "../session" }
futures-util = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
tempfile = { workspace = true }
proptest = { workspace = true }
async-trait = { workspace = true }
